### ISSUE TITLE
ME Bridge, listCells(), and Storage Bus

### ISSUE THREAD

**Issue by CastilloAnthony** [Seniorendi/AdvancedPeripherals#639]
### Describe

When I try to list the cells of an ME network, while there is a storage bus attached somewhere on the network, an error is produced. Removal of said storage bus removes the error and produces the listed cells as expected. For reference I am trying to use this in the all the mods 9 (ATM9) modpack.

### Steps to reproduce

1. CC Computer with ME Bridge to the left.
2. Connect ME Bridge to an ME Network.
3. Attach a Stroage Bus anywhere on the network
4. In the CC Computer lua executor type in: peripheral.wrap('left').listCells()
5. Error gets produced.

### Multiplayer?

No

### Version

1.20.1-0.7.39r (Latest 1.20.1)

### Minecraft, Forge and maybe other related mods versions

Forge 47.2.20, Applied Energistics 2 15.2.4, Advanced Peripherals 0.7.40r, CC: Tweaked 1.111.0

### Screenshots or Videos

https://imgur.com/a/aXIWndD

### Crashlog/log

N/A

**Comment by CastilloAnthony** [comment]
Video showing the error in action: https://youtu.be/YTpvJSxCOZ0

**Comment by SirEndii** [comment]
I thought I fixed that in the latest version oops

**Comment by logicallysound** [comment]
A similar error occurs if there's an ME Chest in the network: https://imgur.com/a/vfajflX

**Comment by Wariie** [comment]
Error still occuring in 1.20.1-0.7.40r
![image](https://github.com/user-attachments/assets/caa0de76-ecc5-4293-970f-6dd4f200bbc6)

**Comment by SirEndii** [comment]
> Error still occuring in 1.20.1-0.7.40r ![image](https://private-user-images.githubusercontent.com/29165721/384660220-caa0de76-ecc5-4293-970f-6dd4f200bbc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNjI2MTgsIm5iZiI6MTczMTI2MjMxOCwicGF0aCI6Ii8yOTE2NTcyMS8zODQ2NjAyMjAtY2FhMGRlNzYtZWNjNS00MjkzLTk3MGYtNmRkNGYyMDBiYmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDE4MTE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3YTk0MWRiMDFiYWE3YzgxZDcwNDMyMjgxYzQ1OGQzM2RiMTMyZGQ0ZWJmNjE3ZTVhNmFkYWQwMDYyOGEzYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KrZ5ST0DIe3esyecort2BJJxYFIwt_8Ir0OXHXG4soI)

can you try 0.7.41

**Comment by SirEndii** [comment]
I will close this now - if someone still sees this issue, feel free to comment/reopen it
