### ISSUE TITLE
Writing in chat throws NullPointerException

### ISSUE THREAD

**Issue by RedCookieLP** [Seniorendi/AdvancedPeripherals#82]
We set up a modded server with a few mods, including Advanced Peripherals.
Everything worked fine, but for some reason, 2 days prior to today, the chat decided to not work...

I looked at the console of the server and it always throws at least three "NullPointerExceptions"... and it seems to throw them in the "onChatTurtle"-method

I don't know how to reproduce the setup since the problem just popped up out of nowhere and we didn't change anything about the server at the moment the problem first popped up...

- Forge Version: 36.1.13 - MC 1.16.5
- AdvancedPeripherals version: 0.6r

**Comment by Seniorendi** [comment]
Hey, could you send me a full snippet of the errors in the console?

**Comment by RedCookieLP** [comment]
![Exception](https://user-images.githubusercontent.com/45202005/119563325-adeb5000-bda7-11eb-81ee-b020ed1cec57.PNG)

**Comment by RedCookieLP** [comment]
That's the whole exception-block

**Comment by Seniorendi** [comment]
Fixed in 0.6.4b

**Comment by frank89722** [comment]
Still happening in 0.6.4b

```
[29.05 09:32:12] [Server] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "dan200.computercraft.shared.computer.core.ServerComputer.queueEvent(String, Object[])" because the return value of "dan200.computercraft.shared.turtle.blocks.TileTurtle.getServerComputer()" is null
[29.05 09:32:12] [Server] 	Index8
[29.05 09:32:12] [Server] 	Listeners:
[29.05 09:32:12] [Server] 		HIGHEST
[29.05 09:32:12] [Server] 		ASM: class com.feed_the_beast.mods.ftbessentials.FTBEEventHandler playerServerChatHighest(Lnet/minecraftforge/event/ServerChatEvent;)V
[29.05 09:32:12] [Server] 		net.minecraftforge.eventbus.EventBus$$Lambda$2760/0x000000080154b598@5feef21f
[29.05 09:32:12] [Server] 		HIGH
[29.05 09:32:12] [Server] 		ASM: class me.shedaniel.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/ServerChatEvent;)V
[29.05 09:32:12] [Server] 		NORMAL
[29.05 09:32:12] [Server] 		ASM: de.erdbeerbaerlp.dcintegration.forge.DiscordIntegration@d2d49b7 chat(Lnet/minecraftforge/event/ServerChatEvent;)V
[29.05 09:32:12] [Server] 		ASM: class de.srendi.advancedperipherals.common.events.Events onChatBox(Lnet/minecraftforge/event/ServerChatEvent;)V
[29.05 09:32:12] [Server] 		ASM: class de.srendi.advancedperipherals.common.events.Events onChatTurtle(Lnet/minecraftforge/event/ServerChatEvent;)V
[29.05 09:32:12] [Server] 		ASM: me.desht.pneumaticcraft.common.event.EventHandlerPneumaticCraft@7d03f1f7 quetziMoo(Lnet/minecraftforge/event/ServerChatEvent;)V
[29.05 09:32:12] [Server] 		ASM: org.dynmap.forge_1_16_5.DynmapPlugin$ChatHandler@454b0193 handleChat(Lnet/minecraftforge/event/ServerChatEvent;)V
[29.05 09:32:12] [Server] 		LOWEST
[29.05 09:32:12] [Server] 		ASM: class com.feed_the_beast.mods.ftbranks.impl.FTBRanksAPIImpl serverChat(Lnet/minecraftforge/event/ServerChatEvent;)V
[29.05 09:32:12] [Server] java.lang.NullPointerExceptionCannot invoke "dan200.computercraft.shared.computer.core.ServerComputer.queueEvent(String, Object[])" because the return value of "dan200.computercraft.shared.turtle.blocks.TileTurtle.getServerComputer()" is null
[29.05 09:32:12] [Server] 	at de.srendi.advancedperipherals.common.events.Events.lambda$onChatTurtle$1(Events.java:60)
[29.05 09:32:12] [Server] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[29.05 09:32:12] [Server] 	at de.srendi.advancedperipherals.common.events.Events.onChatTurtle(Events.java:51)
[29.05 09:32:12] [Server] 	at net.minecraftforge.eventbus.ASMEventHandler_396_Events_onChatTurtle_ServerChatEvent.invoke(.dynamic)
[29.05 09:32:12] [Server] 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
[29.05 09:32:12] [Server] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
[29.05 09:32:12] [Server] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
[29.05 09:32:12] [Server] 	at net.minecraftforge.common.ForgeHooks.onServerChatEvent(ForgeHooks.java:485)
[29.05 09:32:12] [Server] 	at net.minecraft.network.play.ServerPlayNetHandler.func_244548_c(ServerPlayNetHandler.java:1105)
[29.05 09:32:12] [Server] 	at net.minecraft.network.play.ServerPlayNetHandler.func_244545_b(ServerPlayNetHandler.java:303)
[29.05 09:32:12] [Server] 	at net.minecraft.network.play.ServerPlayNetHandler.func_244538_a(ServerPlayNetHandler.java:316)
[29.05 09:32:12] [Server] 	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
[29.05 09:32:12] [Server] 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
[29.05 09:32:12] [Server] 	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
[29.05 09:32:12] [Server] 	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734)
[29.05 09:32:12] [Server] 	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159)
[29.05 09:32:12] [Server] 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
[29.05 09:32:12] [Server] 	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717)
[29.05 09:32:12] [Server] 	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711)
[29.05 09:32:12] [Server] 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103)
[29.05 09:32:12] [Server] 	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696)
[29.05 09:32:12] [Server] 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646)
[29.05 09:32:12] [Server] 	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
[29.05 09:32:12] [Server] 	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by SquTM** [comment]
still happening in newest update 
![image](https://user-images.githubusercontent.com/76019610/120209772-f92db480-c226-11eb-9d1a-5a5f5e27f9dc.png)

**Comment by Seniorendi** [comment]
Do you use a chatty turtle?

**Comment by Gbergz** [comment]
This happens in a newly created world aswell. Just started mining. Nothing from the mod yet.

**Comment by lukeplechaty** [comment]
i found its the chatty turtle spawned in the villages that are doing it when i broke it chat work agen.

**Comment by Seniorendi** [comment]
Fixed in 0.6.6b
